services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gouale_services
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${APP_PORT}:3000"  # Use APP_PORT from environment
    restart: unless-stopped
    networks:
      - app-network
      - frontend

networks:
  app-network:
    driver: bridge
  frontend:
    external: true
